# Setup
title:        前端技术
tagline:      逸飞的前端打怪日常，主要是javascript
baseurl:      "/Front-end-learning"

# About/contact
author:
  name:       逸飞
  url:        https://github.com/panyifei

#Others
markdown: redcarpet

zhihu_username:     pan-yi-fei-41
github_username:    panyifei
jianshu_username:   3b9067fb7edf
