# Setup
title:        前端技术
tagline:      一个前端工程狮的打怪日常，主要是javascript
baseurl:      "/Front-end-learning"

# About/contact
author:
  name:       panyifei
  url:        https://github.com/panyifei

#Others
markdown: kramdown
